module.exports = {
  shooterSpeed: 3,
  bulletSpeed: 7,
  shooterXOffset: 12.5,
  shooterYOffset: 1,
  alienWidth: 25,
  alienHeight: 25,
  rightCanvasOffset: 20,
  alienYMovement: 7,
  mothershipKillPoints: 20,
  alienKillPoints: 1,
  mothershipSpeed: 1.5,
  canvasLeftAlienOffset: 25,
  canvasBottomAlienOffset: 25,
  mothershipTopOffset: 10,
  shooterWidth: 25,
  shooterHeight: 25,
  mothershipWidth: 25,
  mothershipHeight: 25,
  bulletWidth: 2,
  bulletHeight: 10,
  bulletColour: '#d8222c',
  finalScreenTextColour: '#ff0000',
  finalScreenFont: '50px VT323',
  finalScreenText: `You're dead!`,
  aliensPerRow: 15,
  alienXSpace: 25,
  alienYSpace: 25,
  yStart: 25,
  frameEveryMs: 20
}
